version: '3'
services:
  am-test-mysql:
    image: mysql:5.7.30
    container_name: am-test-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 48708:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./db_data/blueprint.sql:/docker-entrypoint-initdb.d/blueprint.sql
    networks:
      - am-test-mysql
  am-test-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: am-test-pma
    ports:
      - 28999:80
    networks:
      - am-test-mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=test
      - PMA_HOSTS=am-test-mysql
networks:
  am-test-mysql:
    driver: bridge
